# Generated by Django 5.1.1 on 2026-08-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='storage_limit_gb',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
